import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Youtube</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div>
        <h1 className='text-3xl'>Youtube clone</h1>
      </div>
    </div>
  )
}
